profesor:
    path:     /
    defaults: { _controller: "GestionBundle:Profesor:index" }

profesor_show:
    path:     /{id}/show
    defaults: { _controller: "GestionBundle:Profesor:show" }

profesor_new:
    path:     /new
    defaults: { _controller: "GestionBundle:Profesor:new" }

profesor_create:
    path:     /create
    defaults: { _controller: "GestionBundle:Profesor:create" }
    requirements: { _method: post }

profesor_edit:
    path:     /{id}/edit
    defaults: { _controller: "GestionBundle:Profesor:edit" }

profesor_update:
    path:     /{id}/update
    defaults: { _controller: "GestionBundle:Profesor:update" }
    requirements: { _method: post|put }

profesor_delete:
    path:     /{id}/delete
    defaults: { _controller: "GestionBundle:Profesor:delete" }
    requirements: { _method: post|delete }

login:
    path: /login
    defaults: { _controller: GestionBundle:Profesor:login }

check_path:
    pattern: /check

logout:
    path: /logout
